version: '3.8'

services:
  nextjs-app:
    build:
      context: .
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - .:/app
    command: npm run dev
    environment:
      - NODE_ENV=development
